on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: github-actions-flake8:latest
          outputs: type=docker,dest=/tmp/github-actions-flake8.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-actions-flake8
          path: /tmp/github-actions-flake8.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-actions-flake8
          path: /tmp

      - name: Load image
        run: docker load --input /tmp/github-actions-flake8.tar

      - name: Test
        run: |
          docker run --rm -t -v "`pwd`/test":/github/workspace github-actions-flake8:latest > output.txt
          cmp --silent output.txt test/expected_output.txt

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Rust Code Formatting
        run: cargo fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Rust Code Style
        run: cargo clippy --all-targets --all-features -- -D warnings
